INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', '1', 'BOX', 'U',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', '10', 'LBS', 'U',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', '11', 'QUAR', 'U',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', '12', 'ITEMS', 'U',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', '13', 'BNDL', 'U',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', '14', 'EACH', 'U',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', '15', 'BBL', 'U',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', '16', 'SET', 'U',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', '17', 'TIN', 'U',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', '18', 'BOTT', 'U',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', '19', 'PKT', 'U',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', '2', 'CAN', 'U',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', '20', 'not good quality', 'R',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', '21', 'DM', 'U',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', '24', 'Dz', 'U',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'IN', NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', '25', 'DAYS', 'U',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'IN', NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', '26', 'RUPEES', 'U',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'UN', NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', '27', 'NO', 'U',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'IN', NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', '28', 'LOT', 'U',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'IN', NULL, '0A', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', '29', 'PER/HRS.', 'U',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'IN', NULL, '0A', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', '3', 'FT', 'U',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', '4', 'GALLON', 'U',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', '5', 'KG', 'U',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', '6', 'LTR', 'U',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', '7', 'ROLL', 'U',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', '8', 'PAIR', 'U',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', '9', 'MTR', 'U',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', 'B', 'By Products', 'C',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', 'F', 'Finished Goods', 'C',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', 'FA', 'Fixed Assets', 'C',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', 'MG', 'Mixed Grade', 'C',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', 'O', 'Others', 'C',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', 'P', 'Spare Parts', 'C',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', 'R', 'Raw Material', 'C',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', 'S', 'Semi-Finished Goods', 'C',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', 'SM', 'Samples', 'C',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO MST_REASON ( VC_COMP_CODE, VC_REASON_CODE, VC_REASON_DESC, VC_REASON_FLG, DT_MOD_DATE,
CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2, VC_FIELD3,
VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', 'T', 'Tools and Dyes', 'C',  TO_Date( '09/07/2008 10:07:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, '01', '01', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
commit;
 
