INSERT INTO MST_CONTROL ( VC_COMP_CODE, VC_CONTROL_CODE, VC_CONTROL_DESC, NU_END_NUMBER,
DT_MOD_DATE, CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2,
VC_FIELD3, VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', 'A', 'PURCHASE PLAN', 0,  TO_Date( '09/07/2008 10:43:30 AM', 'MM/DD/YYYY HH:MI:SS AM')
, ' ', NULL, '01', '01', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL); 
INSERT INTO MST_CONTROL ( VC_COMP_CODE, VC_CONTROL_CODE, VC_CONTROL_DESC, NU_END_NUMBER,
DT_MOD_DATE, CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2,
VC_FIELD3, VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', 'B', 'MATERIAL REQUISITION SLIP', 0,  TO_Date( '09/07/2008 10:43:30 AM', 'MM/DD/YYYY HH:MI:SS AM')
, ' ', NULL, '01', '01', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL); 
INSERT INTO MST_CONTROL ( VC_COMP_CODE, VC_CONTROL_CODE, VC_CONTROL_DESC, NU_END_NUMBER,
DT_MOD_DATE, CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2,
VC_FIELD3, VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', 'D', 'RFQ (PURCHASE)', 0,  TO_Date( '09/07/2008 10:43:30 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'UN', NULL, '01', '01', NULL, NULL, NULL, NULL, 286, NULL, NULL, NULL); 
INSERT INTO MST_CONTROL ( VC_COMP_CODE, VC_CONTROL_CODE, VC_CONTROL_DESC, NU_END_NUMBER,
DT_MOD_DATE, CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2,
VC_FIELD3, VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', 'G', 'PURCHASE ORDER', 0,  TO_Date( '09/07/2008 10:43:30 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'UN', NULL, '01', '01', NULL, NULL, NULL, NULL, 122, NULL, NULL, NULL); 
INSERT INTO MST_CONTROL ( VC_COMP_CODE, VC_CONTROL_CODE, VC_CONTROL_DESC, NU_END_NUMBER,
DT_MOD_DATE, CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2,
VC_FIELD3, VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', 'H', 'STORE DESPATCH REQUEST', 0,  TO_Date( '09/07/2008 10:43:30 AM', 'MM/DD/YYYY HH:MI:SS AM')
, ' ', NULL, '01', '01', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL); 
INSERT INTO MST_CONTROL ( VC_COMP_CODE, VC_CONTROL_CODE, VC_CONTROL_DESC, NU_END_NUMBER,
DT_MOD_DATE, CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2,
VC_FIELD3, VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', 'I', 'RECEIPT', 0,  TO_Date( '09/07/2008 10:43:30 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'UN', NULL, '01', '01', NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL); 
INSERT INTO MST_CONTROL ( VC_COMP_CODE, VC_CONTROL_CODE, VC_CONTROL_DESC, NU_END_NUMBER,
DT_MOD_DATE, CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2,
VC_FIELD3, VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', 'K', 'GATE PASS', 0,  TO_Date( '09/07/2008 10:43:30 AM', 'MM/DD/YYYY HH:MI:SS AM')
, ' ', NULL, '01', '01', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL); 
INSERT INTO MST_CONTROL ( VC_COMP_CODE, VC_CONTROL_CODE, VC_CONTROL_DESC, NU_END_NUMBER,
DT_MOD_DATE, CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2,
VC_FIELD3, VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', 'L', 'DESPATCH', 0,  TO_Date( '09/07/2008 10:43:30 AM', 'MM/DD/YYYY HH:MI:SS AM')
, ' ', NULL, '01', '01', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL); 
INSERT INTO MST_CONTROL ( VC_COMP_CODE, VC_CONTROL_CODE, VC_CONTROL_DESC, NU_END_NUMBER,
DT_MOD_DATE, CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2,
VC_FIELD3, VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', 'P', 'REQUIREMENT AREA MASTER', 0,  TO_Date( '09/07/2008 10:43:30 AM', 'MM/DD/YYYY HH:MI:SS AM')
, ' ', NULL, '01', '01', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL); 
INSERT INTO MST_CONTROL ( VC_COMP_CODE, VC_CONTROL_CODE, VC_CONTROL_DESC, NU_END_NUMBER,
DT_MOD_DATE, CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2,
VC_FIELD3, VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', 'Q', 'REASON MASTER', 0,  TO_Date( '09/07/2008 10:43:30 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'UN', NULL, '01', '01', NULL, NULL, NULL, NULL, 24, NULL, NULL, NULL); 
INSERT INTO MST_CONTROL ( VC_COMP_CODE, VC_CONTROL_CODE, VC_CONTROL_DESC, NU_END_NUMBER,
DT_MOD_DATE, CH_STAT_FLAG, CH_STAT_UP_FLAG, VC_AUTH_CODE, VC_DEFAULT_COMP, VC_FIELD1, VC_FIELD2,
VC_FIELD3, VC_FIELD4, NU_FIELD1, NU_FIELD2, DT_FIELD1, DT_FIELD2 ) VALUES ( 
'01', 'V', 'ISSUES', 0,  TO_Date( '09/07/2008 10:43:30 AM', 'MM/DD/YYYY HH:MI:SS AM')
, ' ', NULL, '01', '01', NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL); 
commit;
 
