prompt 'TABLE NAME MST_REASON:-'

CREATE TABLE MST_REASON
(
  VC_COMP_CODE     VARCHAR2(2)             NOT NULL,
  VC_REASON_CODE   VARCHAR2(4)             NOT NULL,
  VC_REASON_DESC   VARCHAR2(30)            NOT NULL,
  VC_REASON_FLG    VARCHAR2(1)             NOT NULL,
  DT_MOD_DATE      DATE,
  CH_STAT_FLAG     VARCHAR2(2),
  CH_STAT_UP_FLAG  VARCHAR2(2),
  VC_AUTH_CODE     VARCHAR2(2),
  VC_DEFAULT_COMP  VARCHAR2(2),
  VC_FIELD1        VARCHAR2(30),
  VC_FIELD2        VARCHAR2(30),
  VC_FIELD3        VARCHAR2(30),
  VC_FIELD4        VARCHAR2(30),
  NU_FIELD1        NUMBER(20,3),
  NU_FIELD2        NUMBER(20,3),
  DT_FIELD1        DATE,
  DT_FIELD2        DATE
)
;

ALTER TABLE MST_REASON ADD (
  CONSTRAINT PK_COMP_REASON PRIMARY KEY (VC_COMP_CODE, VC_REASON_CODE)   );

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON  MST_REASON TO PUBLIC;

TABLE Name MST_CONTROL:

CREATE TABLE MST_CONTROL
(
  VC_COMP_CODE     VARCHAR2(2)             NOT NULL,
  VC_CONTROL_CODE  VARCHAR2(2)             NOT NULL,
  VC_CONTROL_DESC  VARCHAR2(30)            NOT NULL,
  NU_END_NUMBER    NUMBER(8)                    NOT NULL,
  DT_MOD_DATE      DATE,
  CH_STAT_FLAG     VARCHAR2(2),
  CH_STAT_UP_FLAG  VARCHAR2(2),
  VC_AUTH_CODE     VARCHAR2(2),
  VC_DEFAULT_COMP  VARCHAR2(2),
  VC_FIELD1        VARCHAR2(30),
  VC_FIELD2        VARCHAR2(30),
  VC_FIELD3        VARCHAR2(30),
  VC_FIELD4        VARCHAR2(30),
  NU_FIELD1        NUMBER(20,3),
  NU_FIELD2        NUMBER(20,3),
  DT_FIELD1        DATE,
  DT_FIELD2        DATE
)
;

ALTER TABLE MST_CONTROL ADD (
  CONSTRAINT PK_COMP_CON_CODE PRIMARY KEY (VC_COMP_CODE, VC_CONTROL_CODE));
                
GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON  MST_CONTROL TO PUBLIC;

TABLE NAME MST_GROUP

CREATE TABLE MST_GROUP
(
  VC_COMP_CODE     VARCHAR2(2)             NOT NULL,
  VC_GROUP_CODE    VARCHAR2(4)             NOT NULL,
  VC_GROUP_DESC    VARCHAR2(1000)          NOT NULL,
  VC_REASON_CODE   VARCHAR2(4)             NOT NULL,
  DT_MOD_DATE      DATE,
  CH_STAT_FLAG     VARCHAR2(2),
  CH_STAT_UP_FLAG  VARCHAR2(2),
  VC_AUTH_CODE     VARCHAR2(2),
  VC_DEFAULT_COMP  VARCHAR2(2),
  VC_FIELD1        VARCHAR2(600),
  VC_FIELD2        VARCHAR2(30),
  VC_FIELD3        VARCHAR2(30),
  VC_FIELD4        VARCHAR2(30),
  NU_FIELD1        NUMBER(20,3),
  NU_FIELD2        NUMBER(20,3),
  DT_FIELD1        DATE,
  DT_FIELD2        DATE
)
;


ALTER TABLE MST_GROUP ADD (
  CONSTRAINT PK_MST_GROUP PRIMARY KEY (VC_COMP_CODE, VC_GROUP_CODE)
   );

ALTER TABLE MST_GROUP ADD (
  CONSTRAINT FK_GROUP FOREIGN KEY (VC_COMP_CODE, VC_REASON_CODE) 
    REFERENCES MST_REASON (VC_COMP_CODE,VC_REASON_CODE));


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON  MST_GROUP TO PUBLIC;

TABLE_NAME:  MST_SUB_GROUP


CREATE TABLE MST_SUB_GROUP
(
  VC_COMP_CODE       VARCHAR2(2)           NOT NULL,
  VC_SUB_GROUP_CODE  VARCHAR2(4)           NOT NULL,
  VC_SUB_GROUP_DESC  VARCHAR2(50)          NOT NULL,
  VC_GROUP_CODE      VARCHAR2(4)           NOT NULL,
  DT_MOD_DATE        DATE,
  CH_STAT_FLAG       VARCHAR2(2),
  CH_STAT_UP_FLAG    VARCHAR2(2),
  VC_AUTH_CODE       VARCHAR2(2),
  VC_DEFAULT_COMP    VARCHAR2(2),
  VC_FIELD1          VARCHAR2(30),
  VC_FIELD2          VARCHAR2(30),
  VC_FIELD3          VARCHAR2(30),
  VC_FIELD4          VARCHAR2(30),
  NU_FIELD1          NUMBER(20,3),
  NU_FIELD2          NUMBER(20,3),
  DT_FIELD1          DATE,
  DT_FIELD2          DATE
)
;

CREATE UNIQUE INDEX PK_MST_SUB_GROUP ON MST_SUB_GROUP
(VC_COMP_CODE, VC_SUB_GROUP_CODE);


ALTER TABLE MST_SUB_GROUP ADD (
  CONSTRAINT PK_MST_SUB_GROUP PRIMARY KEY (VC_COMP_CODE, VC_SUB_GROUP_CODE));


ALTER TABLE MST_SUB_GROUP ADD (
  CONSTRAINT FK_SUB_GROUP FOREIGN KEY (VC_COMP_CODE, VC_GROUP_CODE) 
    REFERENCES MST_GROUP (VC_COMP_CODE,VC_GROUP_CODE));


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON  MST_SUB_GROUP TO PUBLIC;


TABLE_NAME: MST_COMPANY

CREATE TABLE MST_COMPANY
(
  VC_DEFAULT_COMP  VARCHAR2(2),
  VC_COMP_CODE     VARCHAR2(2)             NOT NULL,
  VC_COMPANY_NAME  VARCHAR2(30)            NOT NULL,
  VC_CLIENT_CODE   VARCHAR2(10),
  VC_ADDRESS1      VARCHAR2(30),
  VC_ADDRESS2      VARCHAR2(30),
  VC_ADDRESS3      VARCHAR2(30),
  VC_CITY          VARCHAR2(30),
  VC_STATE         VARCHAR2(30),
  VC_COUNTRY       VARCHAR2(50),
  VC_CST_NO        VARCHAR2(20),
  DT_CST_DATE      DATE,
  VC_LST_NO        VARCHAR2(20),
  DT_LST_DATE      DATE,
  VC_TELEPHONE1    VARCHAR2(30),
  VC_TELEPHONE2    VARCHAR2(30),
  CH_AUTH_REQD     CHAR(1),
  VC_PAN_NO        VARCHAR2(25),
  VC_TAN_NO        VARCHAR2(25),
  VC_TDS_CIRCLE    VARCHAR2(50),
  CH_ACTIVE        CHAR(1),
  VC_IEC_NO        VARCHAR2(20),
  VC_ADDRESS4      VARCHAR2(30),
  VC_ADDRESS5      VARCHAR2(30),
  VC_ADDRESS6      VARCHAR2(30),
  VC_ADDRESS7      VARCHAR2(30),
  VC_CLASS_CODE    VARCHAR2(8),
  VC_FAX_NO        VARCHAR2(30),
  VC_EMAIL_NO      VARCHAR2(30),
  VC_CHALLAN_NO    VARCHAR2(4),
  VC_REG_NO        VARCHAR2(30),
  VC_PF_NO         VARCHAR2(30),
  VC_ESI_NO        VARCHAR2(30),
  VC_ECC_NO        VARCHAR2(30),
  VC_DIVISION      VARCHAR2(30),
  VC_RANGE         VARCHAR2(30),
  VC_COMP_INITIAL  VARCHAR2(3),
  CH_STAT_UP_FLAG  CHAR(2),
  CH_STAT_FLAG     CHAR(2),
  DT_MOD_DATE      DATE,
  VC_AUTH_CODE     VARCHAR2(2),
  VC_FIELD1        VARCHAR2(30),
  VC_FIELD2        VARCHAR2(30),
  VC_FIELD3        VARCHAR2(30),
  VC_FIELD4        VARCHAR2(30),
  DT_FIELD1        DATE,
  DT_FIELD2        DATE,
  NU_FIELD1        NUMBER(18,3),
  NU_FIELD2        NUMBER(18,3)
)


ALTER TABLE MST_COMPANY ADD (
  CONSTRAINT PK_COMPANY_CODE PRIMARY KEY (VC_COMP_CODE)
   );


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON  MST_COMPANY TO PUBLIC;



TABLE NAME: FIN_ACCOUNT_YEAR

CREATE TABLE FIN_ACCOUNT_YEAR
(
  VC_COMP_CODE            VARCHAR2(2)      NOT NULL,
  DT_CURRENT_START_DATE   DATE,
  DT_CURRENT_END_DATE     DATE,
  DT_PREVIOUS_START_DATE  DATE,
  DT_PREVIOUS_END_DATE    DATE,
  CH_BOOK_CLOSING_FLAG    CHAR(1),
  NU_ITLIMIT              NUMBER(18,3),
  CH_YEAR_CLOSING_FLAG    CHAR(1),
  VC_DEFAULT_COMP         VARCHAR2(2),
  CH_STAT_FLAG            CHAR(2),
  CH_STAT_UP_FLAG         CHAR(2),
  DT_MOD_DATE             DATE,
  VC_AUTH_CODE            VARCHAR2(2),
  VC_FIELD1               VARCHAR2(30),
  VC_FIELD2               VARCHAR2(30),
  VC_FIELD3               VARCHAR2(30),
  VC_FIELD4               VARCHAR2(30),
  DT_FIELD1               DATE,
  DT_FIELD2               DATE,
  NU_FIELD1               NUMBER(18,3),
  NU_FIELD2               NUMBER(18,3)
);

ALTER TABLE FIN_ACCOUNT_YEAR ADD (
  CONSTRAINT RF_FIN_COMP_CODE FOREIGN KEY (VC_COMP_CODE) 
    REFERENCES MST_COMPANY (VC_COMP_CODE));


TABLE NAME MST_ITEM:-

CREATE TABLE MST_ITEM
(
  VC_DEFAULT_COMP    VARCHAR2(2),
  VC_COMP_CODE       VARCHAR2(2)           NOT NULL,
  VC_ITEM_CODE       VARCHAR2(30)          NOT NULL,
  VC_ITEM_DESC       VARCHAR2(200)         NOT NULL,
  VC_TECH_DESC       VARCHAR2(50),
  NU_BASIC_PRICE     NUMBER(15,4),
  NU_EVAL_RATE       NUMBER(15,4),
  NU_MAX_QTY         NUMBER(12,3),
  NU_MIN_QTY         NUMBER(12,3),
  NU_REORD_QTY       NUMBER(12,3),
  NU_SAFE_QTY        NUMBER(12,3),
  NU_SCRAP_RATE      NUMBER(15,4),
  NU_WASTE_PER       NUMBER(4,2),
  VC_ABC_CLASS       VARCHAR2(1),
  VC_VED_CLASS       VARCHAR2(1),
  VC_UNIT            VARCHAR2(12),
  VC_ALT_ITEM        VARCHAR2(30),
  VC_CLASSIFICATION  VARCHAR2(4),
  VC_MAT_CAT         VARCHAR2(3),
  VC_NATURE          VARCHAR2(1),
  VC_IMPORT_FLG      VARCHAR2(1),
  NU_LEAD_TIME       NUMBER(3),
  NU_OPENING_QTY     NUMBER(12,3),
  QOH_DATE           DATE,
  VC_ITEM_GROUP      VARCHAR2(4),
  VC_UNIT_CODE       VARCHAR2(4),
  VC_LOT_NO          VARCHAR2(6),
  VC_BIN_NO          VARCHAR2(6),
  VC_ITEM_SUB_GROUP  VARCHAR2(4),
  VC_ISSUE_UNIT      VARCHAR2(4),
  NU_CONV_FACTOR     NUMBER(10),
  CH_STAT_UP_FLAG    CHAR(2),
  CH_STAT_FLAG       CHAR(2),
  DT_MOD_DATE        DATE,
  VC_AUTH_CODE       VARCHAR2(2),
  VC_FIELD1          VARCHAR2(30),
  VC_FIELD2          VARCHAR2(30),
  VC_FIELD3          VARCHAR2(30),
  VC_FIELD4          VARCHAR2(30),
  DT_FIELD1          DATE,
  DT_FIELD2          DATE,
  NU_FIELD1          NUMBER(18,3),
  NU_FIELD2          NUMBER(18,3)
)
;
         

TABLE_NAME STOCK_SUMMARY :-

CREATE TABLE STOCK_SUMMARY
(
  VC_COMP_CODE       VARCHAR2(2)           NOT NULL,
  VC_ITEM_CODE       VARCHAR2(30)          NOT NULL,
  NU_QTY_RECEIVED    NUMBER(12,3),
  NU_QTY_DESP        NUMBER(12,3),
  NU_BALANCE_QTY     NUMBER(12,3)               NOT NULL,
  NU_QTY_REJECTED    NUMBER(12,3)               NOT NULL,
  NU_QTY_REWORKABLE  NUMBER(12,3)               NOT NULL,
  NU_QTY_DEFECTIVE   NUMBER(12,3)               NOT NULL,
  NU_QTY_ORDERED     NUMBER(12,3)               NOT NULL,
  NU_QTY_REQUESTED   NUMBER(12,3)               NOT NULL,
  NU_QTY_TO_ORD      NUMBER(12,3)               NOT NULL,
  NU_QTY_AVAILABLE   NUMBER(12,3)               NOT NULL,
  NU_QTY_REQUIRED    NUMBER(12,3)               NOT NULL,
  DT_MOD_DATE        DATE,
  CH_STAT_FLAG       VARCHAR2(2),
  CH_STAT_UP_FLAG    VARCHAR2(2),
  VC_AUTH_CODE       VARCHAR2(2),
  VC_DEFAULT_COMP    VARCHAR2(2),
  VC_FIELD1          VARCHAR2(30),
  VC_FIELD2          VARCHAR2(30),
  VC_FIELD3          VARCHAR2(30),
  VC_FIELD4          VARCHAR2(30),
  NU_FIELD1          NUMBER(20,3),
  NU_FIELD2          NUMBER(20,3),
  DT_FIELD1          DATE,
  DT_FIELD2          DATE
)
;


ALTER TABLE STOCK_SUMMARY ADD (
  CONSTRAINT PK_STOCK PRIMARY KEY (VC_COMP_CODE, VC_ITEM_CODE)
                  );


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON  STOCK_SUMMARY TO PUBLIC;


 
TABLE NAME STK_LOT_SUMMARY :-

CREATE TABLE STK_LOT_SUMMARY
(
  VC_COMP_CODE       VARCHAR2(2)           NOT NULL,
  VC_ITEM_CODE       VARCHAR2(30)          NOT NULL,
  NU_BALANCE_QTY     NUMBER(12,3),
  NU_QTY_REJECTED    NUMBER(12,3),
  NU_QTY_REWORKABLE  NUMBER(12,3),
  NU_QTY_DEFECTIVE   NUMBER(12,3),
  VC_LOT_NO          VARCHAR2(6)           NOT NULL,
  VC_BIN_NO          VARCHAR2(6)           NOT NULL,
  NU_COST            NUMBER(15,4),
  DT_MOD_DATE        DATE,
  CH_STAT_FLAG       VARCHAR2(2),
  CH_STAT_UP_FLAG    VARCHAR2(2),
  VC_AUTH_CODE       VARCHAR2(2),
  VC_DEFAULT_COMP    VARCHAR2(2),
  VC_FIELD1          VARCHAR2(30),
  VC_FIELD2          VARCHAR2(30),
  VC_FIELD3          VARCHAR2(30),
  VC_FIELD4          VARCHAR2(30),
  NU_FIELD1          NUMBER(20,3),
  NU_FIELD2          NUMBER(20,3),
  DT_FIELD1          DATE,
  DT_FIELD2          DATE
);

ALTER TABLE STK_LOT_SUMMARY ADD (
  CONSTRAINT PK_COMP_STK_LOT PRIMARY KEY (VC_COMP_CODE, VC_ITEM_CODE, VC_LOT_NO));

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON  STK_LOT_SUMMARY TO PUBLIC;


TABLE NAME MST_MONTH_SUMMARY:-

CREATE TABLE MST_MONTH_SUMMARY
(
  VC_COMP_CODE          VARCHAR2(2),
  VC_DEFAULT_COMP       VARCHAR2(2),
  DT_FIN_START_DATE     DATE,
  DT_FIN_END_DATE       DATE,
  VC_ITEM_CODE          VARCHAR2(30),
  NU_YEAR_OPEN_BALANCE  NUMBER(18,3),
  NU_ISSUE_04           NUMBER(12,3),
  NU_RECEIPT_04         NUMBER(12,3),
  NU_ISSUE_05           NUMBER(12,3),
  NU_RECEIPT_05         NUMBER(12,3),
  NU_ISSUE_06           NUMBER(12,3),
  NU_RECEIPT_06         NUMBER(12,3),
  NU_ISSUE_07           NUMBER(12,3),
  NU_RECEIPT_07         NUMBER(12,3),
  NU_ISSUE_08           NUMBER(12,3),
  NU_RECEIPT_08         NUMBER(12,3),
  NU_ISSUE_09           NUMBER(12,3),
  NU_RECEIPT_09         NUMBER(12,3),
  NU_ISSUE_10           NUMBER(12,3),
  NU_RECEIPT_10         NUMBER(12,3),
  NU_ISSUE_11           NUMBER(12,3),
  NU_RECEIPT_11         NUMBER(12,3),
  NU_ISSUE_12           NUMBER(12,3),
  NU_RECEIPT_12         NUMBER(12,3),
  NU_ISSUE_01           NUMBER(12,3),
  NU_RECEIPT_01         NUMBER(12,3),
  NU_ISSUE_02           NUMBER(12,3),
  NU_RECEIPT_02         NUMBER(12,3),
  NU_ISSUE_03           NUMBER(12,3),
  NU_RECEIPT_03         NUMBER(12,3),
  NU_TOT_ISSUED         NUMBER(18,3),
  NU_TOT_RECEIVED       NUMBER(18,3),
  CH_STAT_UP_FLAG       CHAR(2),
  CH_STAT_FLAG          CHAR(2),
  DT_MOD_DATE           DATE,
  VC_AUTH_CODE          VARCHAR2(2),
  VC_FIELD1             VARCHAR2(30),
  VC_FIELD2             VARCHAR2(30),
  VC_FIELD3             VARCHAR2(30),
  VC_FIELD4             VARCHAR2(30),
  DT_FIELD1             DATE,
  DT_FIELD2             DATE,
  NU_FIELD1             NUMBER(18,3),
  NU_FIELD2             NUMBER(18,3),
  NU_YEAR_OPEN_COST     NUMBER(15,2)
);


CREATE UNIQUE INDEX PK_MST_MONTH_SUMM ON MST_MONTH_SUMMARY
(VC_COMP_CODE, DT_FIN_START_DATE, DT_FIN_END_DATE, VC_ITEM_CODE)


ALTER TABLE MST_MONTH_SUMMARY ADD (
  CONSTRAINT PK_MST_MONTH_SUMM PRIMARY KEY (VC_COMP_CODE, DT_FIN_START_DATE, DT_FIN_END_DATE, VC_ITEM_CODE));


TRIGGER INSERT_STOCK_RECORDS :-

CREATE OR REPLACE TRIGGER INSERT_STOCK_RECORDS
after insert on makess.mst_item for each row
DECLARE
 fin_start_date   date;
 fin_end_date     date;
Begin

Begin
  select  dt_current_start_date ,dt_current_end_date
  into  fin_start_date,fin_end_date
  from  fin_account_year
  where  vc_comp_code=:new.vc_comp_code
  and ch_year_closing_flag = 'O';
 exception
  when NO_DATA_FOUND then
  select  dt_current_start_date , dt_current_end_date
  into  fin_start_date,fin_end_date
  from  fin_account_year
  where  vc_comp_code=:new.vc_comp_code
  and ch_year_closing_flag = 'C';

 when others then
  raise_application_error(-20101, 'Error encountered with your   financial year') ;
 End;


 
 Insert into stock_summary
 ( vc_comp_code , vc_item_code, NU_BALANCE_QTY, NU_QTY_REJECTED,
 NU_QTY_REWORKABLE, NU_QTY_DEFECTIVE , NU_QTY_ORDERED, NU_QTY_REQUESTED
 , NU_QTY_TO_ORD, NU_QTY_AVAILABLE , NU_QTY_REQUIRED,vc_default_comp)
 values (:new.vc_comp_code , :new.vc_item_code , NVL(:new.nu_opening_qty,0), 0,
 0, 0, 0, 0,
 0, nvl(:new.nu_opening_qty,0), 0 ,:new.vc_default_comp) ;
--2)
 
 Insert into stk_lot_summary
 ( vc_comp_code , vc_item_code, NU_BALANCE_QTY, NU_QTY_REJECTED,
 NU_QTY_REWORKABLE, NU_QTY_DEFECTIVE, VC_LOT_NO, VC_BIN_NO, NU_COST,vc_default_comp,dt_mod_date,ch_stat_flag)
 values (:new.vc_comp_code , :new.vc_item_code , nvl(:new.nu_opening_qty,0), 0,
  0, 0, :new.vc_lot_no, :new.vc_bin_no, nvl(:new.nu_eval_rate,0),:new.vc_default_comp,sysdate,'IN')  ;

--4)

 Insert into mst_month_summary
 ( vc_comp_code, dt_fin_start_date, dt_fin_end_date, vc_item_code,
 nu_year_open_balance, nu_tot_received, vc_default_comp,dt_mod_date,ch_stat_flag)
 values (:new.vc_comp_code ,fin_start_date,fin_END_date, :new.vc_item_code ,
 nvl(:new.nu_opening_qty,0), nvl(:new.nu_opening_qty,0),
 :new.vc_default_comp,sysdate,'IN')  ;

Exception
 when others then
  raise_application_error(-20101, 'Error encountered ') ;
End ;
/
SHOW ERRORS;


ALTER TABLE MST_ITEM ADD (
  CONSTRAINT PK_ITEM PRIMARY KEY (VC_COMP_CODE, VC_ITEM_CODE));


ALTER TABLE MST_ITEM ADD (
  CONSTRAINT FK_ITEM_GROUP FOREIGN KEY (VC_COMP_CODE, VC_ITEM_GROUP) 
    REFERENCES INVENT.MST_GROUP (VC_COMP_CODE,VC_GROUP_CODE));

ALTER TABLE MST_ITEM ADD (
  CONSTRAINT FK_MST_ITEM_CLASS FOREIGN KEY (VC_COMP_CODE, VC_CLASSIFICATION) 
    REFERENCES INVENT.MST_REASON (VC_COMP_CODE,VC_REASON_CODE));


ALTER TABLE MST_ITEM ADD (
  CONSTRAINT FK_MST_ITEM_ISS_UNIT FOREIGN KEY (VC_COMP_CODE, VC_ISSUE_UNIT) 
    REFERENCES INVENT.MST_REASON (VC_COMP_CODE,VC_REASON_CODE));

ALTER TABLE MST_ITEM ADD (
  CONSTRAINT FK_SUB_MST FOREIGN KEY (VC_COMP_CODE, VC_ITEM_SUB_GROUP) 
    REFERENCES INVENT.MST_SUB_GROUP (VC_COMP_CODE,VC_SUB_GROUP_CODE));

ALTER TABLE MST_ITEM ADD (
  CONSTRAINT FK_UNIT FOREIGN KEY (VC_COMP_CODE, VC_UNIT_CODE) 
    REFERENCES INVENT.MST_REASON (VC_COMP_CODE,VC_REASON_CODE));


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON  MST_ITEM TO PUBLIC;

Table Name MST_EXCISE_CHAPTER:-


CREATE TABLE MST_EXCISE_CHAPTER
(
  VC_DEFAULT_COMP    VARCHAR2(2),
  VC_COMP_CODE       VARCHAR2(2)           NOT NULL,
  VC_CHAPTER_CODE    VARCHAR2(12)          NOT NULL,
  DT_EFFECTIVE_DATE  DATE                       NOT NULL,
  CH_DUTY_TYPE       CHAR(1)               NOT NULL,
  NU_DUTY            NUMBER(13,3)               NOT NULL,
  CH_STAT_UP_FLAG    CHAR(2),
  CH_STAT_FLAG       CHAR(2),
  DT_MOD_DATE        DATE,
  VC_AUTH_CODE       VARCHAR2(2),
  VC_FIELD1          VARCHAR2(30),
  VC_FIELD2          VARCHAR2(30),
  VC_FIELD3          VARCHAR2(30),
  VC_FIELD4          VARCHAR2(30),
  DT_FIELD1          DATE,
  DT_FIELD2          DATE,
  NU_FIELD1          NUMBER(18,3),
  NU_FIELD2          NUMBER(18,3)
)


 
Table Name MST_EXCISE_PRODUCT:- 

CREATE TABLE MST_EXCISE_PRODUCT
(
  VC_DEFAULT_COMP  VARCHAR2(2),
  VC_COMP_CODE     VARCHAR2(2)             NOT NULL,
  VC_PRODUCT_CODE  VARCHAR2(30)            NOT NULL,
  VC_CHAPTER_CODE  VARCHAR2(12)            NOT NULL,
  NU_MRP_PER       NUMBER(5,2),
  CH_DECLARED      CHAR(1),
  CH_MRP_RULE      CHAR(1)                 NOT NULL,
  CH_STAT_UP_FLAG  CHAR(2),
  CH_STAT_FLAG     CHAR(2),
  DT_MOD_DATE      DATE,
  VC_AUTH_CODE     VARCHAR2(2),
  VC_FIELD1        VARCHAR2(30),
  VC_FIELD2        VARCHAR2(30),
  VC_FIELD3        VARCHAR2(30),
  VC_FIELD4        VARCHAR2(30),
  DT_FIELD1        DATE,
  DT_FIELD2        DATE,
  NU_FIELD1        NUMBER(18,3),
  NU_FIELD2        NUMBER(18,3)
)

TABLE Name MST_ITEM_INFO:-


CREATE TABLE MST_ITEM_INFO
(
  VC_COMP_CODE           VARCHAR2(2)       NOT NULL,
  VC_ITEM_CODE           VARCHAR2(30)      NOT NULL,
  NU_SPECIFIC_CUST_CODE  NUMBER(6),
  CH_INACTIVE_ITEM_CODE  CHAR(1),
  NU_WEIGHT_PCS          NUMBER(9,3),
  NU_KGS_FOR_PCS         NUMBER(13,3),
  NU_KGS_FACTOR          NUMBER(13,6),
  NU_MIN_STOCK_LEVEL     NUMBER(12,3),
  CH_STAT_FLAG           CHAR(2),
  CH_STAT_UP_FLAG        CHAR(2),
  DT_MOD_DATE            DATE,
  VC_DEFAULT_COMP        VARCHAR2(2),
  VC_AUTH_CODE           VARCHAR2(2),
  VC_FIELD1              VARCHAR2(30),
  VC_FIELD2              VARCHAR2(30),
  VC_FIELD3              VARCHAR2(30),
  VC_FIELD4              VARCHAR2(30),
  NU_FIELD1              NUMBER(20,3),
  NU_FIELD2              NUMBER(20,3),
  DT_FIELD1              DATE,
  DT_FIELD2              DATE
)


 
TABLE Name MST_SUP_ITEM

CREATE TABLE MST_SUP_ITEM
(
  VC_COMP_CODE      VARCHAR2(2)            NOT NULL,
  NU_SUPPLIER_CODE  NUMBER(6)                   NOT NULL,
  VC_ITEM_CODE      VARCHAR2(30)           NOT NULL,
  NU_QUANTITY       NUMBER(10,3),
  NU_PRICE          NUMBER(13,2),
  NU_REJ_ALLOW      NUMBER(4,2),
  NU_LEAD_TIME      NUMBER(3),
  CH_STAT_FLAG      CHAR(2),
  CH_STAT_UP_FLAG   CHAR(2),
  DT_MOD_DATE       DATE,
  VC_DEFAULT_COMP   VARCHAR2(2),
  VC_AUTH_CODE      VARCHAR2(2),
  VC_FIELD1         VARCHAR2(30),
  VC_FIELD2         VARCHAR2(30),
  VC_FIELD3         VARCHAR2(30),
  VC_FIELD4         VARCHAR2(30),
  DT_FIELD1         DATE,
  DT_FIELD2         DATE,
  NU_FIELD1         NUMBER(20,3),
  NU_FIELD2         NUMBER(20,3)
)

TABLE NAME DT_ITEM_LOCATION:-

CREATE TABLE DT_ITEM_LOCATION	
(
  VC_COMP_CODE     VARCHAR2(2)             NOT NULL,
  VC_LOC_CODE      VARCHAR2(4)             NOT NULL,
  VC_ITEM_CODE     VARCHAR2(30)            NOT NULL,
  DT_MOD_DATE      DATE,
  CH_STAT_FLAG     VARCHAR2(2),
  CH_STAT_UP_FLAG  VARCHAR2(2),
  VC_AUTH_CODE     VARCHAR2(2),
  VC_DEFAULT_COMP  VARCHAR2(2),
  VC_FIELD1        VARCHAR2(30),
  VC_FIELD2        VARCHAR2(30),
  VC_FIELD3        VARCHAR2(30),
  VC_FIELD4        VARCHAR2(30),
  NU_FIELD1        NUMBER(20,3),
  NU_FIELD2        NUMBER(20,3),
  DT_FIELD1        DATE,
  DT_FIELD2        DATE
)



 
TABLE NAME MST_COMP_RELATION:-

CREATE TABLE MST_COMP_RELATION
(
  VC_COMP_CODE     VARCHAR2(2)             NOT NULL,
  VC_PARENT_COMP   VARCHAR2(2),
  VC_DEFAULT_COMP  VARCHAR2(2),
  VC_STRUCT_FLAG   VARCHAR2(2)             NOT NULL,
  CH_STAT_UP_FLAG  CHAR(2),
  CH_STAT_FLAG     CHAR(2),
  DT_MOD_DATE      DATE,
  VC_AUTH_CODE     VARCHAR2(2),
  VC_FIELD1        VARCHAR2(30),
  VC_FIELD2        VARCHAR2(30),
  VC_FIELD3        VARCHAR2(30),
  VC_FIELD4        VARCHAR2(30),
  DT_FIELD1        DATE,
  DT_FIELD2        DATE,
  NU_FIELD1        NUMBER(18,3),
  NU_FIELD2        NUMBER(18,3)
)


TABLE NAME MST_SUPPLIER:-

CREATE TABLE MST_SUPPLIER
(
  VC_COMP_CODE                 VARCHAR2(2 BYTE) NOT NULL,
  NU_SUPPLIER_CODE             NUMBER(6)        NOT NULL,
  VC_SUPPLIER_NAME             VARCHAR2(50 BYTE),
  VC_SHIP_ADDRESS1             VARCHAR2(30 BYTE),
  VC_SHIP_ADDRESS2             VARCHAR2(30 BYTE),
  VC_SHIP_ADDRESS3             VARCHAR2(30 BYTE),
  VC_SHIP_CITY                 VARCHAR2(35 BYTE),
  VC_SHIP_STATE                VARCHAR2(35 BYTE),
  VC_SHIP_COUNTRY              VARCHAR2(50 BYTE),
  VC_SHIP_PIN_CODE             VARCHAR2(20 BYTE),
  VC_TELEPHONE                 VARCHAR2(50 BYTE),
  VC_EMAIL                     VARCHAR2(50 BYTE),
  VC_FAX_NO                    VARCHAR2(50 BYTE),
  VC_BANK_NAME                 VARCHAR2(30 BYTE),
  VC_BANK_BRANCH_NAME          VARCHAR2(30 BYTE),
  VC_BANK_ADDRESS1             VARCHAR2(30 BYTE),
  VC_BANK_ADDRESS2             VARCHAR2(30 BYTE),
  VC_BANK_ADDRESS3             VARCHAR2(30 BYTE),
  VC_BANK_CITY                 VARCHAR2(35 BYTE),
  VC_BANK_STATE                VARCHAR2(35 BYTE),
  VC_BANK_COUNTRY              VARCHAR2(50 BYTE),
  VC_BANK_PIN_CODE             VARCHAR2(20 BYTE),
  VC_CONTACT_PERSON            VARCHAR2(30 BYTE),
  VC_CONTACT_PERSON_PHONE      VARCHAR2(50 BYTE),
  VC_BILL_ADDRESS1             VARCHAR2(30 BYTE),
  VC_BILL_ADDRESS2             VARCHAR2(30 BYTE),
  VC_BILL_ADDRESS3             VARCHAR2(30 BYTE),
  VC_BILL_CITY                 VARCHAR2(35 BYTE) NOT NULL,
  VC_BILL_STATE                VARCHAR2(35 BYTE) NOT NULL,
  VC_BILL_COUNTRY              VARCHAR2(50 BYTE) NOT NULL,
  VC_BILL_PIN_CODE             VARCHAR2(20 BYTE),
  VC_LICENSE_NO                VARCHAR2(15 BYTE),
  VC_CST_NO                    VARCHAR2(20 BYTE),
  DT_CST_DATE                  DATE,
  VC_LST_NO                    VARCHAR2(20 BYTE),
  DT_LST_DATE                  DATE,
  VC_CATEGORY_CODE             VARCHAR2(4 BYTE),
  VC_TYPE                      VARCHAR2(4 BYTE),
  NU_CREDIT_DAYS               NUMBER(3),
  VC_TELEX                     CHAR(9 BYTE),
  VC_RATING                    CHAR(1 BYTE),
  NU_DLY_DAYS                  NUMBER(3),
  NU_ACCOUNT_CODE              NUMBER(6),
  NU_CURRENCY_CODE             NUMBER(3)        NOT NULL,
  VC_COUNTRY_CODE              VARCHAR2(3 BYTE),
  VC_PAN_NO                    VARCHAR2(25 BYTE),
  VC_REMARKS                   VARCHAR2(100 BYTE),
  VC_ALT_CONTACT_PERSON        VARCHAR2(30 BYTE),
  VC_ALT_CONTACT_PERSON_PHONE  VARCHAR2(50 BYTE),
  VC_DIVISION_NO               VARCHAR2(35 BYTE),
  VC_COLLECTORATE              VARCHAR2(25 BYTE),
  VC_RANGE                     VARCHAR2(35 BYTE),
  VC_RC_NO                     VARCHAR2(25 BYTE),
  VC_ECC_NO                    VARCHAR2(30 BYTE),
  CH_ACTIVE                    CHAR(1 BYTE),
  VC_PREFIX                    VARCHAR2(2 BYTE),
  VC_BATCH_NO                  VARCHAR2(4 BYTE),
  CH_STAT_FLAG                 CHAR(2 BYTE),
  CH_STAT_UP_FLAG              CHAR(2 BYTE),
  DT_MOD_DATE                  DATE,
  VC_DEFAULT_COMP              VARCHAR2(2 BYTE),
  VC_AUTH_CODE                 VARCHAR2(2 BYTE),
  VC_FIELD1                    VARCHAR2(30 BYTE),
  VC_FIELD2                    VARCHAR2(30 BYTE),
  VC_FIELD3                    VARCHAR2(30 BYTE),
  VC_FIELD4                    VARCHAR2(30 BYTE),
  DT_FIELD1                    DATE,
  DT_FIELD2                    DATE,
  NU_FIELD1                    NUMBER(20,3),
  NU_FIELD2                    NUMBER(20,3)
)

ALTER TABLE MST_SUPPLIER ADD (
  CONSTRAINT PK_SUPPLIER_CODE PRIMARY KEY (VC_COMP_CODE, NU_SUPPLIER_CODE));
ALTER TABLE MST_SUPPLIER ADD (
  CONSTRAINT FK_SUPPLIER_COMP FOREIGN KEY (VC_COMP_CODE) 
    REFERENCES MST_COMPANY (VC_COMP_CODE));

TABLE NAME: HD_PUR_ORDER


CREATE TABLE HD_PUR_ORDER
(
  VC_COMP_CODE             VARCHAR2(2 BYTE)     NOT NULL,
  VC_ORDER_NO              VARCHAR2(10 BYTE)    NOT NULL,
  DT_ORDER_DATE            DATE                 NOT NULL,
  NU_SUPPLIER_CODE         NUMBER(6)            NOT NULL,
  VC_QUOTE_NO              VARCHAR2(60 BYTE),
  VC_ORDER_TYPE            VARCHAR2(1 BYTE)     NOT NULL,
  VC_ORDER_CAT             VARCHAR2(1 BYTE),
  DT_DEL_DATE              DATE,
  VC_TERMS_OF_DEL          VARCHAR2(500 BYTE),
  VC_REMARKS               VARCHAR2(500 BYTE),
  VC_CANCEL_FLG            VARCHAR2(1 BYTE),
  VC_AD_HOC_FLG            VARCHAR2(1 BYTE),
  VC_EXCISE_CODE           VARCHAR2(4 BYTE),
  NU_EXCISE_VALUE          NUMBER(13,2),
  VC_CONSIGNEE             CHAR(1 BYTE),
  VC_FREIGHT               CHAR(1 BYTE),
  NU_FREIGHT_VALUE         NUMBER(13,2),
  NU_FREIGHT_CODE          NUMBER(6),
  CH_C_FORM                VARCHAR2(12 BYTE),
  VC_TERMS_OF_PAYMENT      VARCHAR2(100 BYTE),
  VC_SPL_INSTRUCTIONS      VARCHAR2(30 BYTE),
  VC_PACKING_INSTRUCTIONS  VARCHAR2(30 BYTE),
  VC_TRANSPORT_MODE        VARCHAR2(10 BYTE),
  VC_TRANSPORTER_NAME      VARCHAR2(60 BYTE),
  VC_ENCLOSURE             VARCHAR2(30 BYTE),
  NU_PACKING_FORWARDING    NUMBER(13,2),
  VC_AMENDMENT_NO          VARCHAR2(10 BYTE),
  DT_AMENDMENT_DATE        DATE,
  VC_ORIG_ORDER_NO         VARCHAR2(8 BYTE),
  VC_ORIG_PO_NUMBER        VARCHAR2(8 BYTE),
  VC_COST_TYPE             CHAR(1 BYTE),
  NU_INSUR_AMT             NUMBER(13,2),
  VC_REF_NO                VARCHAR2(15 BYTE),
  CH_PACK_PERC_AMT         CHAR(1 BYTE),
  NU_DISCOUNT              NUMBER(4,2),
  NU_CREDIT_DAYS           NUMBER(3),
  DT_VALID_UPTO            DATE,
  VC_DEL_REQ               VARCHAR2(100 BYTE),
  NU_OCTROI                NUMBER(13,2),
  NU_OCTROI_CODE           NUMBER(6),
  NU_SPL_EXCISE            NUMBER(5,2),
  NU_SPL_EXCISE_CODE       NUMBER(6),
  NU_SURCHARGE             NUMBER(5,2),
  NU_SURCHARGE_CODE        NUMBER(6),
  DT_EFFECTIVE_DATE        DATE,
  NU_DEL_DAYS              NUMBER(3),
  CH_IN_EX_EXCISE          CHAR(1 BYTE),
  CH_IN_EX                 CHAR(1 BYTE),
  CH_EXC_PERC_AMT          CHAR(1 BYTE),
  CH_AUTH_FLAG             CHAR(1 BYTE),
  CH_STAT_FLAG             CHAR(2 BYTE),
  CH_STAT_UP_FLAG          CHAR(2 BYTE),
  DT_MOD_DATE              DATE,
  VC_DEFAULT_COMP          VARCHAR2(2 BYTE),
  VC_AUTH_CODE             VARCHAR2(2 BYTE),
  VC_FIELD1                VARCHAR2(30 BYTE),
  VC_FIELD2                VARCHAR2(30 BYTE),
  VC_FIELD3                VARCHAR2(30 BYTE),
  VC_FIELD4                VARCHAR2(30 BYTE),
  DT_FIELD1                DATE,
  DT_FIELD2                DATE,
  NU_FIELD1                NUMBER(20,3),
  NU_FIELD2                NUMBER(20,3),
  VC_PO_EQUIP              VARCHAR2(70 BYTE),
  NU_DELIVERY_CHARG        NUMBER(8,2)
)

ALTER TABLE HD_PUR_ORDER ADD (
  CONSTRAINT PK_HD_PUR_ORDER PRIMARY KEY (VC_COMP_CODE, VC_ORDER_NO, DT_ORDER_DATE));

ALTER TABLE HD_PUR_ORDER ADD (
  CONSTRAINT FK_ORD_SUPP_CODE FOREIGN KEY (VC_COMP_CODE, NU_SUPPLIER_CODE) 
    REFERENCES MST_SUPPLIER (VC_COMP_CODE,NU_SUPPLIER_CODE));


TABLE NAME: DT_PUR_ORDER

CREATE TABLE DT_PUR_ORDER
(
  VC_COMP_CODE     VARCHAR2(2 BYTE)             NOT NULL,
  VC_ORDER_NO      VARCHAR2(10 BYTE)            NOT NULL,
  VC_ITEM_CODE     VARCHAR2(30 BYTE)            NOT NULL,
  NU_QTY_ORD       NUMBER(10,3),
  NU_PRICE         NUMBER(13,2),
  NU_QTY_RECD      NUMBER(10,3),
  CH_STATUS        VARCHAR2(1 BYTE),
  NU_DISCOUNT      NUMBER(5,2),
  NU_QTY_RECEIVED  NUMBER(10,3),
  DT_ORDER_DATE    DATE,
  CH_STAT_FLAG     CHAR(2 BYTE),
  CH_STAT_UP_FLAG  CHAR(2 BYTE),
  DT_MOD_DATE      DATE,
  VC_DEFAULT_COMP  VARCHAR2(2 BYTE),
  VC_AUTH_CODE     VARCHAR2(2 BYTE),
  VC_FIELD1        VARCHAR2(30 BYTE),
  VC_FIELD2        VARCHAR2(30 BYTE),
  VC_FIELD3        VARCHAR2(30 BYTE),
  VC_FIELD4        VARCHAR2(30 BYTE),
  DT_FIELD1        DATE,
  DT_FIELD2        DATE,
  NU_FIELD1        NUMBER(20,3),
  NU_FIELD2        NUMBER(20,3),
  NU_SP_PRICE      NUMBER(15,3),
  VC_RECEIVE_COMP  VARCHAR2(2 BYTE),
  NU_RIG_QTY       NUMBER(15,3),
  PREVIOUS_PRICE   NUMBER(13,2)
)

ALTER TABLE DT_PUR_ORDER ADD (
  CONSTRAINT PK_DT_PUR_ORDER PRIMARY KEY (VC_COMP_CODE, VC_ORDER_NO, VC_ITEM_CODE, DT_ORDER_DATE));

ALTER TABLE DT_PUR_ORDER ADD (
  CONSTRAINT FK_DT_HD_PUR_ORD FOREIGN KEY (VC_COMP_CODE, VC_ORDER_NO, DT_ORDER_DATE) 
    REFERENCES HD_PUR_ORDER (VC_COMP_CODE,VC_ORDER_NO,DT_ORDER_DATE));

TABLE NAME : ORD_RESULT

CREATE TABLE ORD_RESULT
(
  VC_COMP_CODE         VARCHAR2(2 BYTE)         NOT NULL,
  VC_ORDER_NO          VARCHAR2(10 BYTE)        NOT NULL,
  NU_ACCOUNT_CODE      NUMBER(6),
  VC_LABEL             VARCHAR2(60 BYTE),
  NU_VALUE             NUMBER(13,2),
  CH_ADDED_SUBTRACTED  CHAR(1 BYTE),
  CH_PUR_PRO_FLAG      CHAR(1 BYTE),
  CH_SUB_BASIC_TOTAL   CHAR(1 BYTE),
  DT_ORDER_DATE        DATE,
  NU_SERIAL_NO         NUMBER(3),
  CH_STAT_FLAG         CHAR(2 BYTE),
  CH_STAT_UP_FLAG      CHAR(2 BYTE),
  DT_MOD_DATE          DATE,
  VC_DEFAULT_COMP      VARCHAR2(2 BYTE),
  VC_AUTH_CODE         VARCHAR2(2 BYTE),
  VC_FIELD1            VARCHAR2(30 BYTE),
  VC_FIELD2            VARCHAR2(30 BYTE),
  VC_FIELD3            VARCHAR2(30 BYTE),
  VC_FIELD4            VARCHAR2(30 BYTE),
  DT_FIELD1            DATE,
  DT_FIELD2            DATE,
  NU_FIELD1            NUMBER(20,3),
  NU_FIELD2            NUMBER(20,3)
)

ALTER TABLE ORD_RESULT ADD (
  CONSTRAINT PK_ORD_RES PRIMARY KEY (VC_COMP_CODE, VC_ORDER_NO, DT_ORDER_DATE, CH_PUR_PRO_FLAG, NU_SERIAL_NO));

TABLE NAME: MST_COUNTRY

CREATE TABLE MST_COUNTRY
(
  VC_COMP_CODE      VARCHAR2(2 BYTE),
  VC_COUNTRY_CODE   VARCHAR2(3 BYTE),
  VC_COUNTRY_NAME   VARCHAR2(50 BYTE)           NOT NULL,
  NU_CURRENCY       NUMBER(3)                   NOT NULL,
  VC_CONS_ADD1      VARCHAR2(50 BYTE),
  VC_CONS_ADD2      VARCHAR2(50 BYTE),
  VC_CONS_PHN1      VARCHAR2(15 BYTE),
  VC_CONS_PHN2      VARCHAR2(15 BYTE),
  VC_CONS_FAX1      VARCHAR2(15 BYTE),
  VC_CONS_FAX2      VARCHAR2(15 BYTE),
  VC_IND_EMB_ADD1   VARCHAR2(50 BYTE),
  VC_IND_EMB_ADD2   VARCHAR2(50 BYTE),
  VC_IND_EMB_PHN1   VARCHAR2(15 BYTE),
  VC_IND_EMB_PHN2   VARCHAR2(15 BYTE),
  VC_IND_EMB_FAX1   VARCHAR2(20 BYTE),
  VC_IND_EMB_FAX2   VARCHAR2(20 BYTE),
  VC_CHAMB_OF_COMM  VARCHAR2(50 BYTE),
  CH_STAT_FLAG      CHAR(2 BYTE),
  CH_STAT_UP_FLAG   CHAR(2 BYTE),
  DT_MOD_DATE       DATE,
  VC_DEFAULT_COMP   VARCHAR2(2 BYTE),
  VC_AUTH_CODE      VARCHAR2(2 BYTE),
  VC_FIELD1         VARCHAR2(30 BYTE),
  VC_FIELD2         VARCHAR2(30 BYTE),
  VC_FIELD3         VARCHAR2(30 BYTE),
  VC_FIELD4         VARCHAR2(30 BYTE),
  NU_FIELD1         NUMBER(20,3),
  NU_FIELD2         NUMBER(20,3),
  DT_FIELD1         DATE,
  DT_FIELD2         DATE
)

TABLE NAME: MST_CURRENCY

CREATE TABLE MST_CURRENCY
(
  VC_COMP_CODE         VARCHAR2(2 BYTE)         NOT NULL,
  NU_CURRENCY_CODE     NUMBER(3)                NOT NULL,
  VC_CURR_DESCRIPTION  VARCHAR2(15 BYTE)        NOT NULL,
  VC_CURRENCY_FLAG     VARCHAR2(1 BYTE)         NOT NULL,
  VC_NOTATION          VARCHAR2(15 BYTE)        NOT NULL,
  VC_DEFAULT_COMP      VARCHAR2(2 BYTE),
  CH_STAT_FLAG         CHAR(2 BYTE),
  CH_STAT_UP_FLAG      CHAR(2 BYTE),
  DT_MOD_DATE          DATE,
  VC_AUTH_CODE         VARCHAR2(2 BYTE),
  VC_FIELD1            VARCHAR2(30 BYTE),
  VC_FIELD2            VARCHAR2(30 BYTE),
  VC_FIELD3            VARCHAR2(30 BYTE),
  VC_FIELD4            VARCHAR2(30 BYTE),
  DT_FIELD1            DATE,
  DT_FIELD2            DATE,
  NU_FIELD1            NUMBER(18,3),
  NU_FIELD2            NUMBER(18,3)
)

TABLE NAME: HD_EXCISE

CREATE TABLE HD_EXCISE
(
  VC_DEFAULT_COMP     VARCHAR2(2 BYTE),
  VC_COMP_CODE        VARCHAR2(2 BYTE)          NOT NULL,
  NU_EXCISE_CODE      NUMBER(6)                 NOT NULL,
  VC_EXCISE_NAME      VARCHAR2(30 BYTE)         NOT NULL,
  VC_GROUP_CODE       VARCHAR2(20 BYTE),
  NU_OPENING_BALANCE  NUMBER(13,3),
  VC_OP_BALABCE_TYPE  CHAR(2 BYTE),
  NU_CLOSING_BALANCE  NUMBER(13,3),
  NU_ACCOUNT_CODE     NUMBER(6),
  CH_SAL_PUR_FLAG     CHAR(1 BYTE),
  CH_FLAG             CHAR(1 BYTE),
  CH_STAT_UP_FLAG     CHAR(2 BYTE),
  CH_STAT_FLAG        CHAR(2 BYTE),
  DT_MOD_DATE         DATE,
  VC_AUTH_CODE        VARCHAR2(2 BYTE),
  VC_FIELD1           VARCHAR2(30 BYTE),
  VC_FIELD2           VARCHAR2(30 BYTE),
  VC_FIELD3           VARCHAR2(30 BYTE),
  VC_FIELD4           VARCHAR2(30 BYTE),
  DT_FIELD1           DATE,
  DT_FIELD2           DATE,
  NU_FIELD1           NUMBER(18,3),
  NU_FIELD2           NUMBER(18,3)
)

TABLE NAME : MST_FREIGHT

CREATE TABLE MST_FREIGHT
(
  VC_DEFAULT_COMP     VARCHAR2(2 BYTE),
  VC_COMP_CODE        VARCHAR2(2 BYTE)          NOT NULL,
  NU_FREIGHT_CODE     NUMBER(6)                 NOT NULL,
  VC_FREIGHT_NAME     VARCHAR2(30 BYTE),
  VC_GROUP_CODE       VARCHAR2(20 BYTE),
  NU_OPENING_BALANCE  NUMBER(13,3),
  VC_OP_BALABCE_TYPE  CHAR(2 BYTE),
  NU_CLOSING_BALANCE  NUMBER(13,3),
  NU_ACCOUNT_CODE     NUMBER(6),
  CH_SAL_PUR_FLAG     CHAR(1 BYTE),
  CH_STAT_UP_FLAG     CHAR(2 BYTE),
  CH_STAT_FLAG        CHAR(2 BYTE),
  DT_MOD_DATE         DATE,
  VC_AUTH_CODE        VARCHAR2(2 BYTE),
  VC_FIELD1           VARCHAR2(30 BYTE),
  VC_FIELD2           VARCHAR2(30 BYTE),
  VC_FIELD3           VARCHAR2(30 BYTE),
  VC_FIELD4           VARCHAR2(30 BYTE),
  DT_FIELD1           DATE,
  DT_FIELD2           DATE,
  NU_FIELD1           NUMBER(18,3),
  NU_FIELD2           NUMBER(18,3)
);

TABLE_NAME—MK_USERS

CREATE TABLE MK_USERS
(
  VC_COMP_CODE     VARCHAR2(2 BYTE),
  CH_USER_CODE     CHAR(2 BYTE),
  VC_USER_NAME     VARCHAR2(30 BYTE)            NOT NULL,
  VC_PASSWORD      VARCHAR2(30 BYTE)            NOT NULL,
  CH_USER_ACTIVE   CHAR(1 BYTE)                 DEFAULT 'Y',
  VC_DEFAULT_COMP  VARCHAR2(2 BYTE),
  CH_STAT_FLAG     CHAR(2 BYTE),
  CH_STAT_UP_FLAG  CHAR(2 BYTE),
  DT_MOD_DATE      DATE,
  VC_AUTH_CODE     VARCHAR2(2 BYTE),
  VC_FIELD1        VARCHAR2(30 BYTE),
  VC_FIELD2        VARCHAR2(30 BYTE),
  VC_FIELD3        VARCHAR2(30 BYTE),
  VC_FIELD4        VARCHAR2(30 BYTE),
  DT_FIELD1        DATE,
  DT_FIELD2        DATE,
  NU_FIELD1        NUMBER(18,3),
  NU_FIELD2        NUMBER(18,3)
)

TABLE NAME: MST_TAX_DEDUCTION

CREATE TABLE MST_TAX_DEDUCTION
(
  VC_DEFAULT_COMP      VARCHAR2(2 BYTE),
  VC_COMP_CODE         VARCHAR2(2 BYTE)         NOT NULL,
  NU_ACCOUNT_CODE      NUMBER(6),
  VC_TAX_CODE          VARCHAR2(3 BYTE)         NOT NULL,
  VC_TAX_NAME          VARCHAR2(50 BYTE),
  CH_PERCENT_AMOUNT    CHAR(1 BYTE),
  VC_VALUE             VARCHAR2(10 BYTE),
  CH_ADDED_SUBTRACTED  CHAR(1 BYTE),
  CH_TAX_STYLE         CHAR(1 BYTE),
  CH_STAT_UP_FLAG      CHAR(2 BYTE),
  CH_STAT_FLAG         CHAR(2 BYTE),
  DT_MOD_DATE          DATE,
  VC_AUTH_CODE         VARCHAR2(2 BYTE),
  VC_FIELD1            VARCHAR2(30 BYTE),
  VC_FIELD2            VARCHAR2(30 BYTE),
  VC_FIELD3            VARCHAR2(30 BYTE),
  VC_FIELD4            VARCHAR2(30 BYTE),
  DT_FIELD1            DATE,
  DT_FIELD2            DATE,
  NU_FIELD1            NUMBER(18,3),
  NU_FIELD2            NUMBER(18,3)
)

TABLE NAME:  DGT2WORD

CREATE TABLE DGT2WORD
(
  VALUE  VARCHAR2(8 BYTE),
  LABEL  VARCHAR2(10 BYTE)
)
